version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        # The ECS service name to update
        TaskDefinition: "arn:aws:ecs:ap-south-1:965080479351:task-definition/todo-app"
        LoadBalancerInfo:
          ContainerName: "todo-app"
          ContainerPort: 3000
# hooks:
#   BeforeInstall:
#     - location: scripts/before-install.sh
#       timeout: 300
#       runas: root
#   AfterInstall:
#     - location: scripts/docker-cleanup.sh
#       timeout: 180
#       runas: root
#   AfterAllowTestTraffic:
#     - location: scripts/health-check.sh
#       timeout: 300
#       runas: root
